[platformio]
boards_dir = boards

[env:bootloader]
platform = ch32v
board = genericCH32V006F8U6
board_build.ldscript = src/BootLink.ld
upload_protocol = minichlink
debug_tool = minichlink
monitor_speed = 115200

build_flags =
  -DCH32V00X=1
  -DCH32V006=1
  -Isrc
  -Isrc/Peripheral/inc

build_src_filter =
  +<main.c>
  +<startup_ch32v00X.S>
  +<core_riscv.c>
  +<system_ch32v00X.c>
  +<Peripheral/src/ch32v00X_gpio.c>
  +<Peripheral/src/ch32v00X_rcc.c>
  +<Peripheral/src/ch32v00X_usart.c>
  +<Peripheral/src/ch32v00X_misc.c>
  +<Peripheral/src/ch32v00X_flash.c>

[env:rs485_iap]
platform = ch32v
board = genericCH32V006F8U6
board_build.ldscript = src/BootLink.ld
upload_protocol = minichlink
debug_tool = minichlink
monitor_speed = 115200
board_upload.maximum_size = 3328

build_flags =
  -DCH32V00X=1
  -DCH32V006=1
  -Isrc
  -Isrc/Peripheral/inc

build_src_filter =
  +<main_rs485_iap.c>
  +<startup_ch32v00X_iap.S>
  +<core_riscv.c>
  +<system_ch32v00X.c>
  +<Peripheral/src/ch32v00X_gpio.c>
  +<Peripheral/src/ch32v00X_rcc.c>
  +<Peripheral/src/ch32v00X_usart.c>
  +<Peripheral/src/ch32v00X_misc.c>

[env:heater_iap]
platform = ch32v
board = genericCH32V006F8U6
board_build.ldscript = src/BootLink.ld
upload_protocol = minichlink
debug_tool = minichlink
monitor_speed = 115200
board_upload.maximum_size = 3328

build_flags =
  -DCH32V00X=1
  -DCH32V006=1
  -DDEVICE_TYPE=DEV_TYPE_HEATER
  -DLED_PORT=GPIOC
  -DLED_PIN=GPIO_Pin_4
  -Isrc
  -Isrc/Peripheral/inc

build_src_filter =
  +<main_rs485_iap.c>
  +<startup_ch32v00X_iap.S>
  +<core_riscv.c>
  +<system_ch32v00X.c>
  +<Peripheral/src/ch32v00X_gpio.c>
  +<Peripheral/src/ch32v00X_rcc.c>
  +<Peripheral/src/ch32v00X_usart.c>
  +<Peripheral/src/ch32v00X_misc.c>
